<a href="https://colab.research.google.com/github/LeeTaeHoon97/Get-distance-from-cam/blob/main/Just_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# from numpy import float32
# # import tensorflow as tf

# input_shape = (2, 2, 2)
# x1 = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
# x2 = tf.constant([[[9,10],[11,12]],[[13,14],[15,16]]])

# y = tf.keras.layers.Add()([x1, x2])

# print(x1,x2)

# print("here y")
# print(y)

NameError: name 'tf' is not defined

In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

torch.cuda.is_available() 

e:\miniconda3\envs\torch_env\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


False

In [6]:
print(torch.cuda.device_count())

0


In [7]:

x1=torch.Tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
x2=torch.Tensor([[[9,10],[11,12]],[[13,14],[15,16]]])

y=x1.add(x2)

print(x1,x2)

print("here y")
print(y)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]]) tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])
here y
tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])


In [8]:
x1=torch.randint(1,10,(1,64,26,26))
b,c,h,w=x1.data.size()
x1=x1.view(b,c,h//2,2,w//2,2).contiguous()
x1=x1.permute(0,1,3,5,2,4).contiguous()
x1=x1.view(b,-1,h//2,w//2)
print(x1.data.size())

torch.Size([1, 256, 13, 13])


In [9]:
x1=torch.Tensor(np.arange(1,17).reshape(4,4))
h,w=x1.data.size()
x1=x1.view(h//2,2,w//2,2).contiguous()
print(x1)
x1=x1.permute(1,3,0,2).contiguous()
print("-------------------------")
print(x1)
x1=x1.view(-1,h//2,w//2)
print("-------------------------")
print(x1.data.size())
print(x1)

tensor([[[[ 1.,  2.],
          [ 3.,  4.]],

         [[ 5.,  6.],
          [ 7.,  8.]]],


        [[[ 9., 10.],
          [11., 12.]],

         [[13., 14.],
          [15., 16.]]]])
-------------------------
tensor([[[[ 1.,  3.],
          [ 9., 11.]],

         [[ 2.,  4.],
          [10., 12.]]],


        [[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])
-------------------------
torch.Size([4, 2, 2])
tensor([[[ 1.,  3.],
         [ 9., 11.]],

        [[ 2.,  4.],
         [10., 12.]],

        [[ 5.,  7.],
         [13., 15.]],

        [[ 6.,  8.],
         [14., 16.]]])


In [10]:
#kitti data format
# 1 type Describes the type of object: 'Car', 'Van', 'Truck',
# 'Pedestrian', 'Person_sitting', 'Cyclist', 'Tram',
# 'Misc' or 'DontCare'
# 1 truncated Float from 0 (non-truncated) to 1 (truncated), where
# truncated refers to the object leaving image boundaries
# 1 occluded Integer (0,1,2,3) indicating occlusion state:
# 0 = fully visible, 1 = partly occluded
# 2 = largely occluded, 3 = unknown
# 1 alpha Observation angle of object, ranging [-pi..pi]
# 4 bbox 2D bounding box of object in the image (0-based index):
# contains left, top, right, bottom pixel coordinates
# 3 dimensions 3D object dimensions: height, width, length (in meters)
# 3 location 3D object location x,y,z in camera coordinates (in meters)
# 1 rotation_y Rotation ry around Y-axis in camera coordinates [-pi..pi]
# https://github.com/NVIDIA/DIGITS/issues/992

In [15]:
print(6084/13/13)

36.0


In [22]:

x=torch.tensor([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[11,22],[33,44]],[[55,66],[77,88]]]])

# a= x.unsqueeze(3)
z= x
# print(z)
z= x[...,1].unsqueeze(3)
# print(z)

In [105]:
aa = torch.tensor([[0,0],[1,1],[2,2],[3,3]])
aa[idx]


tensor([[0, 0],
        [3, 3],
        [3, 3],
        [3, 3]])

In [100]:
aa

tensor([[16,  2,  3,  4],
        [ 9, 10, 11,  1],
        [ 5,  6,  7,  8],
        [12, 13, 14, 15]])